config/routes.rb
Gordo::Application.routes.draw do
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders, only: [:create, :destroy, :index] do
    get 'toggle_delivery', :on => :member
  end
  resources :food_items do
    get 'toggle_active', :on => :member
    collection do
      get 'active'
    end
  end
  resources :charges do
    collection do
      post 'charge'
    end
  end

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/how_its_work',    to: 'static_pages#how_its_work',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/cancellation', to: 'orders#cancellation', via: 'get'
  post '/forget_password_token', to: 'users#forget_password_token'
  match '/forget_password', to: 'users#forget_password', via: 'get'
  get '/new_password/:token', to: 'users#new_password', as: :reset_new_password

  resources :users do
    get 'waiting', :on => :member
    get 'check_delivered'
    get 'check_delivered_order', :on => :member
    post 'reset_password', :on => :member
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @order  = current_user.orders.build
      #TODO: remove....
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  def how_its_work
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<body class="body_orange">
  
  <section class="orange">
  	<div class="container main_container">
    	<div class="how_its_work_con">
            <div class="row">
                <div class="col-md-12">
                    <div class="about_gordo">
                         <h2>About Gordo</h2>
                         <div class="gordo_img"><img src="/assets/aboutIcons.png"/></div>
                         <p>Gordo is food, now. </p>
                         <p>Delivery is super rapid, fun and hassle-free. </p>
                         <p>It is not about choice, it is about convenience. </p>
                         <p>We make the decision thoughtless and delivery always on time. </p>
                         <p>It’s like magic! </p>
                         <div class="mobile_login_logo">
                            <a class="mobile_logo" href="#"><img src="/assets/mobile_logo.png"/></a>
                        </div>  
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn_purple btn-lg btn-block" href="/signin">Order Now!</a>
                </div>
            </div>
        </div>
    </div>	
    
  </section>
</body>

app/views/static_pages/contact.html.erb
<%# provide(:title, 'Contact') %>
<!-- <h1>Contact</h1>
<p>
  If you would like to contact us us, please e-mail Gordo at  <a href="mailto:team@gordo.com">team@gordo.com</a>.
</p> -->

<body class="body_orange">
    
  <section class="orange">
  	<div class="container main_container">
    	<div class="how_its_work_con">
            <div class="row">
                <div class="col-md-12">
                    <div class="about_gordo">
                         <h2>Contact Us!</h2>
                         <p>Get in touch with any questions or comments. We’d love to hear from you!</p>
                          <div class="mobile_login_form">
                            <form>
                                <div class="form-group">
                                  <input type="text" id="login-name" placeholder="Name" value="" class="form-control login-field">
                                </div>
                                <div class="form-group">
                                  <input type="text" id="login-name" placeholder="Email" value="" class="form-control login-field">
                                </div>
                                <div class="form-group">
                                  <input type="text" id="login-name" placeholder="Order Number (Optional)" value="" class="form-control login-field">
                                  <label for="login-pass" class="login-field-icon fui-check-inverted"></label>
                                </div>
                                <div class="form-group">
                                  <textarea rows="6" id="login-name" placeholder="Message" value="" class="form-control login-field"></textarea>
                                </div>
                                <a href="#" class="btn btn_purple btn-lg btn-block">Send Message</a>
                            </form>
                    </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>	
    
  </section>
</body>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  If you have any questions or need help, please e-mail us at <a href="mailto:team@getgordo.com">team@getgordo.com</a>
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <script type="text/javascript">
    window.location.href="/users/<%= @current_user.id %>"
  </script>
<% else %>
<section class="orange">
        <div class="container main_container">
                <!-- <div class="row">
                  <div class="col-md-12">
                    <header>
                        <nav class="navbar navbar-default" role="navigation">
                          <div class="container-fluid"> -->
                            <!-- Brand and toggle get grouped for better mobile display -->
                            <!-- <div class="navbar-header">
                              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                              </button>
                              <a class="navbar-brand" href="/signin"><img src="/assets/gordo-logo-198.png"/></a>
                            </div> -->
                        
                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <!-- <div class="collapse navbar-collapse custom_menu" id="bs-example-navbar-collapse-1">
                              <ul class="nav navbar-nav">
                                <li class="active"><a href="#">How it Works</a></li>
                                <li><a href="#">About Gordo</a></li>
                                <li><a href="#">My Account</a></li>
                                <li><%#= link_to "Login", signin_path %></li>
                              </ul>
                            </div> --><!-- /.navbar-collapse -->
                          <!-- </div> --><!-- /.container-fluid -->
                        <!-- </nav>
                    </header>
                  </div>
                </div> -->
                <div class="row">
                  <div class="col-md-12">
                      <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
                          <ol class="carousel-indicators">
                            <li data-target="#carousel-example-captions" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-captions" data-slide-to="1" class=""></li>
                            <li data-target="#carousel-example-captions" data-slide-to="2" class=""></li>
                          </ol>
                          <div class="carousel-inner">
                            <div class="item active">
                              <img src="/assets/banner1.jpg"/>
                              <div class="carousel-caption">
                                <h2>Food delivery in <%= Gordo::Application::DELIVERY_PROMISE %> minutes or less.</h2>
                                <div class="order_btn"><a class="btn btn_purple btn-lg" href="/signin">Order Now!</a></div>
                              </div>
                            </div>
                            <div class="item">
                              <img src="/assets/banner1.jpg"/>
                              <div class="carousel-caption">
                                <h2>Wherever you are.</h2>
                                <div class="order_btn"><a class="btn btn_purple btn-lg" href="/signin">Order Now!</a></div>
                              </div>
                            </div>
                            <div class="item">
                              <img src="/assets/banner1.jpg"/>
                              <div class="carousel-caption">
                                <h2>It's like magic!</h2>
                                <div class="order_btn"><a class="btn btn_purple btn-lg" href="/signin">Order Now!</a></div>
                              </div>
                            </div>
                          </div>
                          
                        </div>
                    </div>
                </div>
        </div>
  </section>
  <section class="purple">
    <div class="container main_container">
        <div class="row">
            <div class="col-md-4 col-xs-12">
              <div class="about_gordo">
                    <h2>About Gordo</h2>
                    <div><img src="/assets/aboutIcons.png"/></div>
                    <ul>
                    </ul>
                </div>
            </div>
            <div class="col-md-8 col-xs-12">
              <div class="body_text about_gordo_text">
                <p>Gordo is food, now.</p>
                <p>Delivery is super rapid, fun and hassle-free.</p>
                <p>It is not about choice, it is about convenience.</p>
                <p>We make the decision thoughtless and delivery always on time.</p>
                <p>It’s like magic!</p>
              </div>
            </div>
        </div>
    </div>
  </section>
  <section class="orange bottom_h320">
    <div class="container main_container">
      <div class="row">
          <div class="col-md-12">
              <div class="how_its_work">
                  <h2>How it Works</h2>
                    <p>Gordo is simple! In just three steps, you’ll have fresh local meals delivered to your doorstep!</p>
                </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-12">
                    <div class="stepsCon">
                      <ul>
                        <li>
                          <span><img src="/assets/step1-110.png"/></span>
                          <p>Create a new account or login.</p>
                        </li>
                        <li>
                          <span><img src="/assets/step2-110.png"/></span>
                          <p>Choose your meal and review your order.</p>
                        </li>
                        <li>
                          <span><img src="/assets/step3-110.png"/></span>
                          <p>Confirm your information, and the order is complete!</p>
                        </li>
                      </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>  
  </section>
  <section class="orange">
    <footer>
      <div class="container main_container">
             <div class="row">
                <div class="col-md-7 col-xs-12">
                    <ul class="footer_nav">
                      <li><a href="/contact">Contact Us</a></li>
                        <li><a href="#">FAQs</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li class="copyright">Gordo © 2014</li>                            
                    </ul>
                </div>
                <div class="col-md-5 col-xs-12">
                  <ul class="footer_social">
                  </ul>
                </div>
             </div>
         </div>
    </footer>
  </section>
 <!--  <div class="center hero-unit">
    <h1>Gordo App</h1>

    <h2>
      This is the home page for the
      <a href="http://getgordo.com/">Gordo</a>
      - feeding you since 2014.
    </h2>

    <%#= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>

  <%#= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %> -->
  <script>
    $('.carousel').carousel({
      interval: 2000
    })
  </script>
<% end %>

app/views/static_pages/how_its_work.html.erb
<body class="body_orange">
  <section class="orange">
    <div class="container main_container">
      <div class="how_its_work_con">
            <div class="row">
                <div class="col-md-12">
                    <div class="how_its_work">
                         <h2>How it Works!</h2>
                         <p>Gordo is simple! In just three steps, you’ll have fresh local meals delivered to your doorstep!</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="stepsCon">
                        <ul>
                            <li>
                                <span><img src="/assets/step1-87.png"/></span>
                                <p>Create a new account or login.</p>
                            </li>
                            <li>
                                <span><img src="/assets/step2-87.png"/></span>
                                <p>Choose your meal and review your order.</p>
                            </li>
                            <li>
                                <span class="last"><img src="/assets/step3-87.png"/></span>
                                <p>Confirm your information, and the order is complete!</p>
                            </li> 
                        </ul>
                    </div>
                </div>
            </div>
       
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn_purple btn-lg btn-block" href="/signin">Order Now!</a>
                </div>
            </div>
        </div>
    </div>  
    
  </section>
</body>