config/routes.rb
Gordo::Application.routes.draw do
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders, only: [:create, :destroy, :index] do
    get 'toggle_delivery', :on => :member
  end
  resources :food_items do
    get 'toggle_active', :on => :member
    collection do
      get 'active'
    end
  end
  resources :charges do
    collection do
      post 'charge'
    end
  end

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/how_its_work',    to: 'static_pages#how_its_work',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/cancellation', to: 'orders#cancellation', via: 'get'
  post '/forget_password_token', to: 'users#forget_password_token'
  match '/forget_password', to: 'users#forget_password', via: 'get'
  get '/new_password/:token', to: 'users#new_password', as: :reset_new_password

  resources :users do
    get 'waiting', :on => :member
    get 'check_delivered'
    get 'check_delivered_order', :on => :member
    post 'reset_password', :on => :member
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('paid DESC, delivered ASC, created_at DESC') }
  validates :address, presence: true, length: { maximum: 100 }
  validates :user_id, presence: true
  validates :food_item_id, presence: true
  validates :quantity, presence: true,
            :numericality => {:greater_than_or_equal_to => 1,
                              :less_than_or_equal_to => Gordo::Application::MAX_QUANTITY}
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy, :toggle_delivery]
  before_action :correct_user,   only: [:destroy, :show]
  before_action :admin_user, only: [:index, :toggle_delivery]

  def index
    @orders = Order.paginate(page: params[:page])
  end

  def create
    if get_pending_order != nil
      flash[:error] = "You already have an open order!"
      route_selector
      return
    end
    @order = current_user.orders.build(order_params)
    if @order.save
      redirect_to user_path(@current_user)
    else
      # Try to redirect him back to the Add Order page if we have a food_item_id
      if @order.food_item_id != nil
        @food_item = FoodItem.find(@order.food_item_id)
        render :template => "food_items/show"
      else
        redirect_to user_path(@current_user)
      end
    end
  end

  def toggle_delivery
    @order = Order.find(params[:id])
    @order.toggle!(:delivered)
  end

  def destroy
    if @order.paid || @order.delivered
      flash[:error] = "You cannot delete an order you've paid for!"
    else
      @order.destroy
    end
    route_selector
  end

  def cancellation
    @order = get_pending_order
    @food_item = @order == nil ? nil : FoodItem.find(@order.food_item_id)
  end

  # def receipt
  #   @order = get_pending_order
  #   @food_item = @order == nil ? nil : FoodItem.find(@order.food_item_id) 
  # end

  private

    def order_params
      params.require(:order).permit(:address, :quantity, :food_item_id)
    end

    def correct_user
      @order = current_user.orders.find_by(id: params[:id])
      redirect_to root_url if @order.nil?
    end
end

app/helpers/orders_helper.rb
module OrdersHelper

  def delivery_link_text(order)
    order.delivered? ? 'Mark as Not Delivered' : 'Mark as Delivered'
  end

  def is_delivered_text(order)
    order.delivered? ? 'Delivered' : 'Delivery Pending'
  end

  def is_paid_text(order)
    order.paid? ? 'Paid' : 'Payment Pending'
  end

  def wrap(address)
    sanitize(raw(address.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<!--  <li>
  <span class="title">Item: <%#= pluralize(order.quantity, @food_item.title) %></span>
  <span class="address">
    Delivering to: <%#= wrap(order.address) %>
  </span>
  <span class="timestamp">
    Placed <%#= time_ago_in_words(order.created_at) %> ago.
  </span>
  <span class="action">
    <%#= link_to "confirm order", charge_charges_path, method: :post,
                                     title: "Yum yum!" %>
    <%#= link_to "cancel", order, method: :delete,
                                     data: { confirm: "Are you sure you want to delete?" },
                                     title: @food_item.title %>
  </span>
</li -->


<body class="body_orange">
  <section class="orange">
    <div class="container main_container">
      <div class="row">
          <div class="col-md-12">
              <div class="mobile_login_steps">
                  <div class="step_show">
                      <div class="step_left pull-left right_strip">
                          <h2>Confirm</br>Details</h2>
                        </div>
                        <div class="step_center bottom_strip order_confirm">
                          <img src="/assets/mobile_step4.png"/>
                        </div>
                        <div class="order_confirm_text">
                          <p><%= order.quantity.to_s + "x " + @food_item.title %></p>
                          <p>$<%= '%.2f' % (order.quantity * @food_item.price) %> in <%= Gordo::Application::DELIVERY_PROMISE %>  min </p>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        <% d = DateTime.now %>
        <div class="row">
          <div class="col-md-12">
                <div class="food_detail_con">
                    <div class="food_detail">
                        <div class="food_item">
                            <a class="food_dish">
                                <img src="<%= @food_item.picture_url %>"/> 
                            </a>
                        </div>
                        <div class="selected_item_detail">
                              <div class="tooltip bottom in" style="">
                                    <div class="tooltip-arrow"></div>
                                    <div class="tooltip-inner">
                                      <div class="order_confirm_box">
                                          <p class=""><%= d.strftime("%A, %B %-dth, %Y") %></p>
                                            <h2>$<%= '%.2f' % (order.quantity * @food_item.price) %></h2>
                                            <p>Will charge credit card on file</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </div>
                    <div class="deliverd_to">
                      <p class="cancel_topgap"></p>
                        <p><a href="/cancellation" class="btn btn_orange btn-lg btn-block">Cancel Your Order</a></p>
                        <!-- <p><a href="/charges/charge" class="btn btn_purple btn-lg btn-block">Place Your Order!</a></p> -->
                        <p><%= link_to "Place Your Order!", charge_charges_path , method: :post,
                                     title: "Yum yum!", class: "btn btn_purple btn-lg btn-block" %></p>
                    </div>
                </div>
            </div>
        </div>
        
        </div>
    </div>  
  </section>
</body>

app/views/orders/cancellation.html.erb
<body class="body_orange">
  <section class="orange">
  	<div class="container main_container">
    	<div class="row">
        	<div class="col-md-12">
            	<div class="mobile_login_steps">
                	<div class="step_show">
                    	<div class="step_left pull-left right_strip">
                        	<h2>Are you</br>Sure?</h2>
                        </div>
                        <div class="step_center order_confirm">
                        	<img src="/assets/mobile_step5.png"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
        	<div class="col-md-12">
                <div class="cancellation_con">
                	<div class="cancellation_form">
                    	<h3>No Gordo 4 You?</h3>
                        <h1>WHY?Not</h1>
                        <form>
                            <div class="btn-group select select-block">
                            	<button class="btn dropdown-toggle clearfix btn-white" data-toggle="dropdown">
                                <span class="filter-option pull-left" id="choose">Meh, Not Hungry</span>&nbsp;<span class="caret"></span>
                                </button><span class="dropdown-arrow"></span>
                                <ul class="dropdown-menu dropdown-inverse" role="menu" style="max-height: 195px; overflow-y: auto; min-height: 108px;">
                                    <li rel="0"><a tabindex="-1" href="#" class="select_option" id="hero">I changed my mind!</a></li>
                                    <li rel="1"><a tabindex="-1" href="#" class="select_option" id="spider">Spider Man arrive and kissed me</a></li>
                                    <li rel="2"><a tabindex="-1" href="#" class="select_option" id="wolv">Ohh yeah baby baby!</a></li>
                                    </ul>
                                </div>
                            <div class="form-group">
                              <textarea class="form-control login-field" value="" placeholder="Please share your concerns" id="login-name"></textarea>
                            </div>
                        </form>
                        <div class="confirm_cancel_btn">
                        <p class="text">We would love to know how how we can improve Gordo for next time</p>
                        <p><%= link_to "Confirm Cancellation", @order, method: :delete, title: @food_item.title, class: "btn btn_purple btn-lg btn-block" %></p>	
                        <!-- <p><a href="#" class="btn btn_purple btn-lg btn-block">Confirm Cancellation</a></p> -->
                    </div>
                    </div>
                    
                </div>
            </div>
        </div>
        </div>
    </div>	
  </section>
  <script>
       $(".select_option").click(function(){
        var text = $(this).text();
        $("#choose").text(text);
       })
  </script>
</body>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<% provide(:title, 'Orders') %>
<h1>Orders</h1>

<%= will_paginate %>

<ul class="food_items">
  <% @orders.each do |order| %>
    <li>
      <% fi = FoodItem.find(order.food_item_id) %>
      <% user = User.find(order.user_id) %>
      <% #= link_to pluralize(order.quantity, fi.title), fi %>
      <%= order.id %>
      | <%= link_to user.name, user %>
      | <%= pluralize(order.quantity, fi.title) %>
      | <%= link_to order.address, "http://maps.google.com/maps?q=#{order.address}", :target => "_blank" %>
      | <%= link_to "GMap", "comgooglemaps://?q=#{order.address}", :target => "_blank" %>
      | <%= is_paid_text(order) %>
      | <%= content_tag :span, is_delivered_text(order),
                  :id => "delivery_status_#{order.id}" %>
      | <%= link_to delivery_link_text(order),
                  toggle_delivery_order_path(order),
                  :remote => true,
                  :id => "delivery_link_#{order.id}" %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @order.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @order.lng %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/toggle_delivery.js.erb
$("#delivery_link_<%= @order.id %>").text("<%= delivery_link_text(@order) %>");
$("#delivery_status_<%= @order.id %>").text("<%= is_delivered_text(@order) %>");