config/routes.rb
Gordo::Application.routes.draw do
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders, only: [:create, :destroy, :index] do
    get 'toggle_delivery', :on => :member
  end
  resources :food_items do
    get 'toggle_active', :on => :member
    collection do
      get 'active'
    end
  end
  resources :charges do
    collection do
      post 'charge'
    end
  end

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/how_its_work',    to: 'static_pages#how_its_work',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/cancellation', to: 'orders#cancellation', via: 'get'
  post '/forget_password_token', to: 'users#forget_password_token'
  match '/forget_password', to: 'users#forget_password', via: 'get'
  get '/new_password/:token', to: 'users#new_password', as: :reset_new_password

  resources :users do
    get 'waiting', :on => :member
    get 'check_delivered'
    get 'check_delivered_order', :on => :member
    post 'reset_password', :on => :member
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create]

  def new
  end

  def create
    customer = Stripe::Customer.create(
      :email => current_user.email,
      :description => "Payments for: #{current_user.name}",
      :card  => params[:stripeToken]
    )
    current_user.update_attribute(:stripe_customer_id, customer.id)
    route_selector

  rescue Stripe::CardError => e
    process_error e
  end

  def charge
    order = get_pending_order
    food_item = FoodItem.find(order.food_item_id)
    Stripe::Charge.create(
      :amount => (order.quantity * food_item.price * 100).round,
      :currency => "usd",
      :customer => current_user.stripe_customer_id
    )

    # At this point the order has been paid for
    order.update_attribute(:paid, true)
    route_selector
  rescue Stripe::CardError => e
    process_error e
  end

  private
    def process_error e
      flash[:error] = e.message
      current_user.update_attribute(:stripe_customer_id, "")
      redirect_to new_charge_path
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%#= form_tag charges_path do %>
  <!--<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%#= Rails.configuration.stripe[:publishable_key] %>"
          data-label="Enter Credit Card Info"
          data-name="Gordo"
          data-description="Food Now!"
          data-email="<%#= current_user.email %>"
          data-allow-remember-me=false
          data-panel-label="Submit"></script>-->
<%# end %>

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_live_52p0lpFKLY3a8S3Rycnbs5yu');
  // 
</script>

<body class="body_orange">
	<section class="orange">
  	<div class="container main_container">
    	<div class="row">
        	<div class="col-md-12">
            	<div class="mobile_login_logo mobile_logo_top">
                    <a class="mobile_logo" href="#"><img src="/assets/mobile_logo_top.png"/></a>
                </div>
            	<div class="mobile_login_steps">
                	<div class="step_show">
                    	<div class="step_left pull-left">
                        	<h2>Login/ </br>Sign Up</h2>
                        </div>
                        <div class="step_center">
                        	<img src="/assets/mobile_step1.png"/>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        
        
      <div class="row">
        <div class="col-md-12">
          <div class="mobile_login_form">
                  
            <form action="/charges" method="post" id="payment-form">
              <span class="payment-errors"></span>
                      <div class="row">
                        <div class="col-xs-9">
                            <div class="form-group">
                              <input type="text" size="20" data-stripe="number" class="form-control login-field" value="" placeholder="Credit Card Number"/>
                            </div>
                        </div>
                        <div class="col-xs-3">
                          <div class="form-group">
                              <input type="text" size="4" data-stripe="cvc" class="form-control login-field credit_cvv" value="" placeholder="CCV"/>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                          <div class="col-xs-6">
                            <div class="form-group">
                                <input type="text" size="2" data-stripe="exp-month" class="form-control login-field" value="" placeholder="Expiraton(Month)"/>
                            </div>
                        </div>
                        <div class="seprator">
                            /
                        </div>
                        <div class="col-xs-6">
                          <div class="form-group">
                              <input type="text" size="2" data-stripe="exp-year" class="form-control login-field" value="" placeholder="Expiraton(Year)"/>
                          </div>
                        </div>

                      </div>
                      
                  <button type="submit" class="btn btn_purple btn-lg btn-block info_submit">Order Now!</button>
                
            </form>
          </div>
        </div>
      </div>
        
        
    </div>	
  </section>
</body>