config/routes.rb
Gordo::Application.routes.draw do
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders, only: [:create, :destroy, :index] do
    get 'toggle_delivery', :on => :member
  end
  resources :food_items do
    get 'toggle_active', :on => :member
    collection do
      get 'active'
    end
  end
  resources :charges do
    collection do
      post 'charge'
    end
  end

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/how_its_work',    to: 'static_pages#how_its_work',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/cancellation', to: 'orders#cancellation', via: 'get'
  post '/forget_password_token', to: 'users#forget_password_token'
  match '/forget_password', to: 'users#forget_password', via: 'get'
  get '/new_password/:token', to: 'users#new_password', as: :reset_new_password

  resources :users do
    get 'waiting', :on => :member
    get 'check_delivered'
    get 'check_delivered_order', :on => :member
    post 'reset_password', :on => :member
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://getgordo.com/">Gordo</a>
    by Team Faty
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%#= link_to "gordo app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%#= link_to "Home", root_path %></li>
          <li><%#= link_to "Help", help_path %></li>
          <%# if signed_in? %>
            <%# if current_user.admin? %>
              <li><%#= link_to "Users", users_path %></li>
              <li><%#= link_to "Orders", orders_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Food Items <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%#= link_to "List Food Items",  food_items_path %></li>
                  <li><%#= link_to "Add Food Item",    new_food_item_path %></li>
                </ul>
              </li>
            <%# end %>

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%#= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%#= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <%# else %>
            <li><%#= link_to "Sign in", signin_path %></li>
          <%# end %>
        </ul>
      </nav>
    </div>
  </div>
</header> -->

<section class="orange">
        <div class="container main_container">
                <div class="row">
                  <div class="col-md-12">
                    <header>
                        <nav class="navbar navbar-default" role="navigation">
                          <div class="container-fluid">
                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header">
                              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                              </button>
                              <a class="navbar-brand" href="/signin"><img src="/assets/gordo-logo-198.png"/></a>
                            </div>
                        



                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <div class="collapse navbar-collapse custom_menu" id="bs-example-navbar-collapse-1">
                              <ul class="nav navbar-nav">
                                <li class="active"><a href="/">Home</a></li>
                                <!-- <li><a href="/how_its_work">How it Works</a></li> -->
                                <li><a href="/about">About</a></li>
                                <% if signed_in? %>
                                  <% if current_user.admin? %>
                                    <li><%= link_to "Users", users_path %></li>
                                    <li><%= link_to "Orders", orders_path %></li>
                                  <li class="dropdown">
                                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Food Items<b class="caret"></b></a>
                                  <ul class="dropdown-menu">
                                    <li><%= link_to "List Food Items",  food_items_path %></li>
                                    <li><%= link_to "Add Food Item",    new_food_item_path %></li>
                                  </ul>
                                </li>
                                  <% end %>

                                  <li class="dropdown">
                                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                                  <ul class="dropdown-menu">
                                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                                    <li class="divider"></li>
                                    <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                                  </ul>
                                </li>
                                <% else %>
                                <li><%= link_to "Sign In", signin_path %></li>
                                <% end %>
                              </ul>
                            </div><!-- /.navbar-collapse -->
                          </div><!-- /.container-fluid -->
                        </nav>
                    </header>
                  </div>
                </div>
              </div>
</section>

<script>
  // $('.dropdown-toggle').click(function() {
  //         $(this).parent().addClass('open');
  //   });

  $( ".dropdown-toggle" ).toggle(function() {
      $(this).parent().addClass('open');
    }, function() {
      $(this).parent().removeClass('open');
    });
  </script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
   <link href='//fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
     <div class="container"> 
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
    </div>

      <%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    <!-- </div> -->
  </body>
</html>